export { MastersComponent } from './masters.component';
export { EmployeeInBranchComponent } from './employee-in-branch/employee-in-branch.component';
export { EmployeeComponent } from './employee/employee.component';
export { TanksComponent } from './tank/tank.componet';
export { PumpComponent } from './pump/pump.component';
export { MSHSDRatesComponent} from './mshsdrates/mshsdrates.component';
export { MemberMasterComponent } from './member-master/member-master.component';
export { VehicleComponent } from './member-master/vehicle/vehicle.component';
export { DesignationComponent } from './designation/designation.component';
export { DepartmentComponent } from './department/department.component';
export { GiftMasterComponent} from './member-master/Giftmaster/giftmaster.component';